### ISSUE TITLE
Support java 17 record classes

### ISSUE THREAD

**Issue by linusnorton** [cronn/reflection-util#13]
At the moment using PropertyUtils.getPropertyName on a record will create an exception: `java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types`.

Is there any way to support records or is it dependant on subclassing?

**Comment by bwaldvogel** [comment]
Supporting records is not that easy since the classes are final and we cannot use our existing proxy mechanism to capture the invoked method.

However, I’ve experimented with another approach that could work. I would appreciate any feedback. You can find the current draft in https://github.com/cronn/reflection-util/pull/15.

**Comment by linusnorton** [comment]
I'm not familiar with ByteBuddy so I can't comment on how RecordSupport is working but from the tests it looks like it will work well

**Comment by bwaldvogel** [comment]
Available in version `2.12.0`

**Comment by linusnorton** [comment]
Excellent, seems to work perfectly
